# Generated by Django 4.1.4 on 2022-12-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=300)),
                ('is_published', models.BooleanField()),
            ],
        ),
    ]
